name: Haskell CI

on: [push]
name: build
jobs:
  runhaskell:
    name: Yahoo Prices
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.0.2'
          cabal-version: '3.4.0.0'
      - run: cabal new-build --enable-tests --enable-benchmarks all